"""
Report template helpers for consistent formatting.
"""

from __future__ import annotations

# Severity emoji mapping
SEVERITY_EMOJI = {
    "critical": "🔴",
    "major": "🟠",
    "minor": "🟡",
    "info": "🔵",
}

# Category emoji mapping
CATEGORY_EMOJI = {
    "security": "🔒",
    "performance": "⚡",
    "bug": "🐛",
    "concurrency": "🧵",
    "error_handling": "⚠️",
    "code_style": "🎨",
    "maintainability": "📦",
    "best_practice": "✅",
    "potential_issue": "❓",
}

MARKDOWN_FOOTER = """
---
<sub>🤖 Generated by [ai-pr-reviewer](https://github.com/pengxueqi616-commits/ai-pr-reviewer)</sub>
"""
