"""
Abstract LLM provider interface.

Defines the contract that all LLM providers (Anthropic, OpenAI, local) must
implement. This abstraction lets the analysis engine operate independently of
the underlying model API.

Design rationale:
- Streaming is part of the interface from day one — non-streaming providers
  simply yield a single chunk
- The ``complete()`` method returns an async generator so the caller can
  process tokens incrementally (progress bars, live preview, etc.)
- Provider configuration (model name, temperature, max tokens) is passed
  via a ``ProviderConfig`` dataclass rather than through the interface,
  keeping it clean and extensible
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import AsyncGenerator


@dataclass
class Message:
    """A single message in a chat conversation."""

    role: str  # "system", "user", "assistant"
    content: str


@dataclass
class ProviderConfig:
    """Configuration for an LLM provider."""

    model: str
    api_key: str
    max_tokens: int = 4096
    temperature: float = 0.3  # lower temperature for more deterministic reviews
    timeout_seconds: int = 120


@dataclass
class CompletionResult:
    """Result of a completed LLM call."""

    content: str
    model: str
    input_tokens: int = 0
    output_tokens: int = 0
    finish_reason: str = ""

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens


class LLMProvider(ABC):
    """Abstract base class for LLM providers."""

    def __init__(self, config: ProviderConfig) -> None:
        self._config = config

    @property
    def config(self) -> ProviderConfig:
        return self._config

    @abstractmethod
    async def complete(
        self,
        messages: list[Message],
        **kwargs,
    ) -> AsyncGenerator[str, None]:
        """Send messages to the LLM and stream the response.

        Args:
            messages: List of messages forming the conversation.

        Yields:
            Text chunks as they are generated by the model.
        """
        ...

    async def complete_with_result(
        self,
        messages: list[Message],
        **kwargs,
    ) -> CompletionResult:
        """Non-streaming convenience wrapper around ``complete()``.

        Collects all chunks and returns a ``CompletionResult`` with token counts.
        """
        chunks: list[str] = []
        async for chunk in self.complete(messages, **kwargs):
            chunks.append(chunk)
        full_content = "".join(chunks)

        return CompletionResult(
            content=full_content,
            model=self._config.model,
        )

    @abstractmethod
    def estimate_tokens(self, messages: list[Message]) -> int:
        """Estimate the total token count for a message list.

        Used by the context builder to decide when to split analysis units.
        """
        ...
